threads: 1

bowtie2:
  idx: 'data/external/ref/idx/bowtie2/index'
  maxins: 2000

bamfilter:
  remove: 1804
  keep: 2
  mapqual: 10

macs2:
  qvalue: 0.05
  gsize: mm

blklist_regions: 'data/external/ref/fa/blacklist_regions.bed'

methods:
  genome_name: 'mm10'

ataqv:
  organism: mouse
  tssfile: 'data/external/ref/misc/ataqv_tss_file.bed'

bamcoverage_bw:
  # --binSize, -bs   
  # Size of the bins, in bases, 
  # for the output of the bigwig/bedgraph file. (Default: 50)
  bin_size: 10

  # --smoothLength   
  # The smooth length defines a window, 
  # larger than the binSize, to average the number of reads. 
  # For example, if the –binSize is set to 20 and the –smoothLength is set to 60, 
  # then, for each bin, the average of the bin and its left and right neighbors 
  # is considered. Any value smaller than –binSize will be ignored and no smoothing 
  # will be applied.
  smooth_length: 30

  # --normalizeUsing 
  #   Possible choices: RPKM, CPM, BPM, RPGC, None   Use one of the entered
  # methods to normalize the number of reads per bin.    By default, no normalization is
  # performed. RPKM = Reads Per Kilobase per Million mapped reads;    CPM = Counts Per
  # Million mapped reads, same as CPM in RNA-seq; BPM = Bins Per Million mapped reads,   
  # same as TPM in RNA-seq; RPGC = reads per genomic content (1x normalization);   
  # Mapped reads are considered after blacklist filtering (if applied).    RPKM (per bin)
  # = number of reads per bin / (number of mapped reads (in millions) * bin length
  # (kb)).    CPM (per bin) = number of reads per bin / number of mapped reads (in
  # millions).    BPM (per bin) = number of reads per bin / sum of all reads per bin (in
  # millions).    RPGC (per bin) = number of reads per bin / scaling factor for 1x average
  # coverage.    None = the default and equivalent to not setting this option at all.   
  # This scaling factor, in turn, is determined from the sequencing    depth: (total
  # number of mapped reads * fragment length) / effective genome size.    The scaling
  # factor used is the inverse of the sequencing depth computed for the    sample to
  # match the 1x coverage. This option requires –effectiveGenomeSize.    Each read is
  # considered independently, if you want to only count one mate from a    pair in paired-end
  # data, then use the –samFlagInclude/–samFlagExclude options. (Default: None)
  normalize_using: 'CPM'

