$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  threads:
    type: integer
  labname:
    type: string
  platform:
    type: string
  trimgalore:
    type: object
    properties:
      quality:
        type: integer
      stringency:
        type: integer
      e:
        type: number
      length:
        type: integer
    required:
      - quality
      - stringency
      - e
  bowtie:
    type: object
    properties:
      max_multiple_aln:
        type: integer
      max_aln_per_read:
        type: integer
      chunkmbs:
        type: integer
      idx:
        type: string
    required:
      - max_multiple_aln
      - max_aln_per_read
      - chunkmbs
      - idx
  bowtie2:
    type: object
    properties:
      idx: 
        type: string
      maxins: 
        type: integer
    required:
      - idx
  filter_bam:
    type: object
    properties:
      pe_keep_reads_flags:
        type: integer
      pe_remove_reads_flags:
        type: integer
      se_remove_reads_flags:
        type: integer
      mapqual_filter:
        type: integer
  macs2:
    type: object
    properties:
      qvalue: 
        type: number
      gsize: 
        type: string
    required:
      - qvalue
      - gsize
  blklist_regions:
    type: string
  methods:
    type: object
    properties:
      genome_name: 
        type: string
  ataqv:
    type: object
    properties:
      organism:
        type: string
      tssfile:
        type: string
    required:
      - organism
      - tssfile
  bamcoverage_bw:
    type: object
    properties:
      bin_size:
        type: integer
      smooth_length:
        type: integer
      normalize_using:
        type: string
      read_extension_length:
        type: integer
    required:
      - bin_size
      - smooth_length
      - normalize_using
      - read_extension_length


required:
  - threads
  - platform
  - trimgalore
  - bowtie2
  - filter_bam
  - macs2
  - blklist_regions
  - ataqv
  - bamcoverage_bw
